# 项目配置优先级：
# resources/application.yml
# jar包所在目录application.yml
# 环境变量
# 命令行参数

spring:
  config:
      import: classpath:application-secret.yml
#       需要参考application-secret.yml.example，在application.yml所在目录下自行配置application-secret.yml
  application:
    name: big-event
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    # 开启下划线命名到驼峰命名的转换，保证可以返回数据库中的时间

jwt:
  expirationTime: 15
  # jwt令牌过期时间，单位分钟，作用于生成的jwt令牌过期时间和redis过期时间



